ARGS:
 tab: 'pw3d_challenge'
 eval_dataset: 'pw3d_challenge'
 GPUS: 0
 model_version: 1
 
 val_batch_size: 64
 nw_eval: 2
 eval: True
 collision_aware_centermap: False
 collision_factor: 0.2
 calc_PVE_error: False

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2
 model_precision: 'fp32'

 old_version: True
 gmodel_path: /home/yusun/ROMP/trained_models/ROMP_hrnet32.pkl
 dataset_rootdir: "/media/yusun/Extreme SSD/dataset/3DPW" #'/path/to/dataset/3DPW'
 output_dir: '/home/yusun/ROMP/results/' #'/path/to/vibe_db where 3dpw_test_db.pt located'