ARGS:
 tab: 'pw3d_test'
 eval_dataset: 'pw3d_test'
 GPUS: 0
 model_version: 1
 
 val_batch_size: 64
 nw_eval: 2
 eval: True
 collision_aware_centermap: False
 collision_factor: 0.2
 calc_PVE_error: False

 backbone: 'hrnet'
 centermap_size: 64
 centermap_conf_thresh: 0.2
 model_precision: 'fp32'

 old_version: True
 gmodel_path: ../trained_models/ROMP_hrnet32.pkl #  '../trained_models/ROMP_resnet50.pkl'
 dataset_rootdir: '/media/yusun/Extreme SSD/dataset/3DPW' #'/path/to/dataset/3DPW'
 annot_dir: '/home/yusun/ROMP_EVAL/data/vibe_db' #'/path/to/vibe_db where 3dpw_test_db.pt located'