
ARGS:
 tab: 'webcam'
 GPUS: 0 
 multi_person: True
 kernel_sizes: [5]
 use_coordmaps: True
 fine_tune: True
 eval: False

 backbone: 'hrnet'
 input_size: 512
 centermap_size: 64
 model_precision: 'fp32'
 val_batch_size: 1
 gmodel_path: '../trained_models/ROMP_hrnet32.pkl' #'../trained_models/ROMP_hrnet32+CAR.pkl' #  '../trained_models/ROMP_resnet50.pkl'
 demo_image_folder: None
 save_mesh: False
 save_centermap: False
 save_dict_results: False
 show_single: True

 webcam: True
 cam_id: 0
 multiprocess: False
 run_on_remote_server: False
 server_ip: 'localhost'
 server_port: 10086
 
 webcam_mesh_color: 'male_tex' # 'male_tex' for using the male texture; 'female_tex' for using the female texture; 'ghostwhite'/'LightCyan' for using the single color texture.
